#!/bin/bash
# This script will start compilation my .c files
UNITY_PATH="../Unity/src/unity.c"

echo 'Вы собираетесь запустить тесты? Если нет, нажмите ENTER.'
read userInput

if [ -n "$userInput" ]; then
    echo "Удаление старых исполняемых файлов тестирования..."
    rm $(find . -maxdepth 1 -type f -name 'test_*')
    echo "Тесты запускаются..."
    gcc $(find . -type f -name '*.c' ! -name main.c) $UNITY_PATH -o test_$(date +%H%M) > /dev/null

    if [ $? -eq 0 ]; then
        ./test_$(date +%H%M)
    fi
else
    gcc main.c variables.c alice/alice_monthly_payment.c common/expenses.c
    if [ $? -eq 0 ]; then
        ./a.out
    fi
fi
